# Generated by Django 4.2.23 on 2025-08-12 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_password_changed_at_user_security_answer_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.RemoveField(
            model_name='passwordhistory',
            name='created_at',
        ),
        migrations.AddField(
            model_name='passwordhistory',
            name='changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='password_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_logins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_answer_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
