# Generated by Django 4.2.23 on 2025-08-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passwordhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
