# Generated by Django 4.2.23 on 2025-08-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_security_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_locked',
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='failed_logins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
