# Generated by Django 4.2.23 on 2025-08-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_user_is_locked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='security_answer_hash',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='security_question',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
