# Generated by Django 4.2.23 on 2025-08-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_security_answer_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_auth_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_auth_event_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_auth_event_ok',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_auth_event_ua',
            field=models.TextField(blank=True, null=True),
        ),
    ]
