# Generated by Django 4.2.23 on 2025-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='details',
            new_name='user_agent',
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
    ]
