# Generated by Django 4.2.23 on 2025-08-12 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("menu", "0002_menuitem_category_menuitem_image_menuitem_tags"),
        ("orders", "0001_initial"),
    ]

    operations = [
        # Keep Order rows sorted newest-first
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-created_at"]},
        ),

        # Add a related_name to Order.customer (helps reverse lookups)
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                to=settings.AUTH_USER_MODEL,
                on_delete=django.db.models.deletion.CASCADE,
                limit_choices_to={"role": "customer"},
                related_name="orders",
            ),
        ),

        # Introduce the new through model for line items
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("notes", models.CharField(max_length=255, blank=True)),
                ("price_at_order", models.DecimalField(max_digits=8, decimal_places=2, null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("menu_item", models.ForeignKey(
                    to="menu.menuitem",
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name="order_items",
                )),
                ("order", models.ForeignKey(
                    to="orders.order",
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name="order_items",
                )),
            ],
            options={
                "verbose_name": "Order Line Item",
                "verbose_name_plural": "Order Line Items",
                "unique_together": {("order", "menu_item")},
            },
        ),

        # IMPORTANT: Do NOT alter Order.items here.
        # 0003 will copy data from the existing M2M into OrderItem,
        # and 0004 will remove the old M2M field.
    ]
