# Generated by Django 4.2.23 on 2025-08-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
